//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
//using System.Data.EntityClient;
//using System.Data.Objects;
//using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Server
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DBEntities object using the connection string found in the 'DBEntities' section of the application configuration file.
        /// </summary>
        public DBEntities() : base("name=DBEntities", "DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBEntities object.
        /// </summary>
        public DBEntities(string connectionString) : base(connectionString, "DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBEntities object.
        /// </summary>
        public DBEntities(EntityConnection connection) : base(connection, "DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CapitalsTable> CapitalsTables
        {
            get
            {
                if ((_CapitalsTables == null))
                {
                    _CapitalsTables = base.CreateObjectSet<CapitalsTable>("CapitalsTables");
                }
                return _CapitalsTables;
            }
        }
        private ObjectSet<CapitalsTable> _CapitalsTables;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CapitalsTables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCapitalsTables(CapitalsTable capitalsTable)
        {
            base.AddObject("CapitalsTables", capitalsTable);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="CapitalsTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CapitalsTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CapitalsTable object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static CapitalsTable CreateCapitalsTable(global::System.Int32 id)
        {
            CapitalsTable capitalsTable = new CapitalsTable();
            capitalsTable.Id = id;
            return capitalsTable;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> lat
        {
            get
            {
                return _lat;
            }
            set
            {
                OnlatChanging(value);
                ReportPropertyChanging("lat");
                _lat = StructuralObject.SetValidValue(value, "lat");
                ReportPropertyChanged("lat");
                OnlatChanged();
            }
        }
        private Nullable<global::System.Decimal> _lat;
        partial void OnlatChanging(Nullable<global::System.Decimal> value);
        partial void OnlatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> lng
        {
            get
            {
                return _lng;
            }
            set
            {
                OnlngChanging(value);
                ReportPropertyChanging("lng");
                _lng = StructuralObject.SetValidValue(value, "lng");
                ReportPropertyChanged("lng");
                OnlngChanged();
            }
        }
        private Nullable<global::System.Decimal> _lng;
        partial void OnlngChanging(Nullable<global::System.Decimal> value);
        partial void OnlngChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String country
        {
            get
            {
                return _country;
            }
            set
            {
                OncountryChanging(value);
                ReportPropertyChanging("country");
                _country = StructuralObject.SetValidValue(value, true, "country");
                ReportPropertyChanged("country");
                OncountryChanged();
            }
        }
        private global::System.String _country;
        partial void OncountryChanging(global::System.String value);
        partial void OncountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String iso2
        {
            get
            {
                return _iso2;
            }
            set
            {
                Oniso2Changing(value);
                ReportPropertyChanging("iso2");
                _iso2 = StructuralObject.SetValidValue(value, true, "iso2");
                ReportPropertyChanged("iso2");
                Oniso2Changed();
            }
        }
        private global::System.String _iso2;
        partial void Oniso2Changing(global::System.String value);
        partial void Oniso2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String iso3
        {
            get
            {
                return _iso3;
            }
            set
            {
                Oniso3Changing(value);
                ReportPropertyChanging("iso3");
                _iso3 = StructuralObject.SetValidValue(value, true, "iso3");
                ReportPropertyChanged("iso3");
                Oniso3Changed();
            }
        }
        private global::System.String _iso3;
        partial void Oniso3Changing(global::System.String value);
        partial void Oniso3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> population
        {
            get
            {
                return _population;
            }
            set
            {
                OnpopulationChanging(value);
                ReportPropertyChanging("population");
                _population = StructuralObject.SetValidValue(value, "population");
                ReportPropertyChanged("population");
                OnpopulationChanged();
            }
        }
        private Nullable<global::System.Int32> _population;
        partial void OnpopulationChanging(Nullable<global::System.Int32> value);
        partial void OnpopulationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> profit
        {
            get
            {
                return _profit;
            }
            set
            {
                OnprofitChanging(value);
                ReportPropertyChanging("profit");
                _profit = StructuralObject.SetValidValue(value, "profit");
                ReportPropertyChanged("profit");
                OnprofitChanged();
            }
        }
        private Nullable<global::System.Int32> _profit;
        partial void OnprofitChanging(Nullable<global::System.Int32> value);
        partial void OnprofitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> identifier
        {
            get
            {
                return _identifier;
            }
            set
            {
                OnidentifierChanging(value);
                ReportPropertyChanging("identifier");
                _identifier = StructuralObject.SetValidValue(value, "identifier");
                ReportPropertyChanged("identifier");
                OnidentifierChanged();
            }
        }
        private Nullable<global::System.Int64> _identifier;
        partial void OnidentifierChanging(Nullable<global::System.Int64> value);
        partial void OnidentifierChanged();

        #endregion

    }

    #endregion

}
